### ISSUE TITLE
Cannot find module tailwind css

### ISSUE THREAD

**Issue by etteryand0** [devo-unicorn/mpit2021prep#2]
npm run build crashes with this error
```
> mpit2021prp@0.1.0 build /usr/share/nginx/actions-runner/_work/mpit2021prep/mpit2021prep
> craco build

(node:7599) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tailwindcss'
Require stack:
- /usr/share/nginx/actions-runner/_work/mpit2021prep/mpit2021prep/craco.config.js
- /usr/share/nginx/actions-runner/_work/mpit2021prep/mpit2021prep/node_modules/@craco/craco/lib/config.js
- /usr/share/nginx/actions-runner/_work/mpit2021prep/mpit2021prep/node_modules/@craco/craco/scripts/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/nginx/actions-runner/_work/mpit2021prep/mpit2021prep/craco.config.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:7599) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7599) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by etteryand0** [comment]
The root of the issue is that github actions uses `npm install` instead of `yarn`
